name: acceptance tests

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  run-acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Acceptance Tests
        run: make acceptance-test
